### ISSUE TITLE
Help with your script

### ISSUE THREAD

**Issue by s0u007** [Kiminaze/ContextMenu#6]
Hi mate is possible to get your discord or better communitator due to the fact that I have many questions not at all issues. If not here are two main things. 

Is it possible to change this deafault cursor for something else ? Is it possible to  change the cursor colour when it is pointing at correct object ?

**Comment by Kiminaze** [comment]
As this has already been answered in our Discord, I'll close this issue.

Tl`dr for the people that still want the answers:
- Read the Readme regarding support ;)
- Color cannot be changed as far as I know.
- Cursor Sprite: https://docs.fivem.net/natives/?_0x8DB8CFFD58B62552
